# Generated by Django 5.0.1 on 2024-01-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawingtables',
            old_name='avatar',
            new_name='drawing',
        ),
    ]
