# Generated by Django 5.0.1 on 2024-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0002_rename_avatar_drawingtables_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingtables',
            name='drawing',
            field=models.FileField(default='drw/test.pdf', upload_to='drw'),
        ),
    ]
