# Generated by Django 5.0.1 on 2024-01-15 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0004_drawingtables_details_drawingtables_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingtables',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час'),
        ),
    ]
