# Generated by Django 5.0.1 on 2024-01-16 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0005_drawingtables_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('picture', models.ImageField(default='post_img/news.jpg', upload_to='post_img', verbose_name='Зображення')),
                ('details', models.TextField(default='test', verbose_name='Інформація')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
