# Generated by Django 5.0.1 on 2024-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingtables',
            name='type',
            field=models.CharField(default='test', max_length=50, verbose_name='Тип столу'),
        ),
    ]
